### ISSUE TITLE
ImportError: No module named 'git'

### ISSUE THREAD

**Issue by dwisiswant0** [em-corp/f0x#4]
Sorry if I'm wrong, I've installed the `python-git` dependency; still get errors like:

```
Traceback (most recent call last):
  File "f0x.py", line 14, in <module>
    from git import Repo
ImportError: No module named 'git'
```

Which module should I install? Can you please add to `requirements` file too?

**Comment by dineshsaini** [comment]
you have to install git-repo for that.
command is $pip3 install git-repo
you can also refer to this link: https://stackoverflow.com/questions/28483253/importerror-no-module-named-git-after-reformatting-laptop

BTW this repo is abandoned, i've no longer access to it. 
use this repo instead https://github.com/dineshsaini/f0x

**Comment by dwisiswant0** [comment]
Thanks @dineshsaini! Will take a look then.
